esphome:
  name: opentherm-boiler
  libraries:
    - "OpenTherm Library"

esp32:
  board: nodemcu-32s

wifi:
  ssid: ''            #Enter wifi ssid
  password:           #Enter wifi password
  fast_connect: true

logger:

api:
  encryption:
    key:              #Enter key
  services:
    - service: set_target_temperature
      variables:
        temp: float
      then:
        - lambda: |-
            id(ot)->set_target_temperature(temp);
            
ota:
  password: ''        #Enter password

external_components:
  - source: github://Hagakurje/ESPHome_OpenTherm_Boiler
    components: [ opentherm ]

opentherm:
  id: ot
  in_pin: 21
  out_pin: 22

sensor:
  - platform: template
    name: "Boiler target temperature"
    lambda: |-
      return id(ot)->target_temperature;
    update_interval: 5s
    unit_of_measurement: °C
    accuracy_decimals: 0  
  - platform: template
    name: "Boiler Temperature"
    lambda: |-
      return id(ot)->boiler_temperature;
    update_interval: 5s
    unit_of_measurement: °C
    accuracy_decimals: 0  
  - platform: template
    name: "Boiler modulation"
    lambda: |-
      return id(ot)->boiler_modulation;
    update_interval: 5s
    unit_of_measurement: '%'
    accuracy_decimals: 0

binary_sensor:
  - platform: template
    name: "Boiler central heating"
    lambda: |-
      return id(ot)->central_heating;